site_url: https://armatanalytics.netlify.app/
logo_url: https://armatanalytics.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/images
public_folder: /images

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'reporting'
    label: 'Reporting'
    folder: 'content/reporting'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'reporting/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Icon', name: 'icon', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Sort Key', name: 'sortkey', widget: 'number', required: false }
  - name: 'dataManagement'
    label: 'Data Management'
    folder: 'content/dataManagement'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'dataManagement/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Icon', name: 'icon', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Icon Background Color', name: 'color', widget: 'color', allowInput: true }
      - { label: 'Sort Key', name: 'sortkey', widget: 'number', required: false }
  - name: 'aboutus'
    label: 'About us'
    folder: 'content/aboutus'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'aboutus/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
  - name: 'ourmission'
    label: 'Our mission'
    folder: 'content/ourmission'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'ourmission/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
  - name: 'ourservices'
    label: 'Our Services'
    folder: 'content/ourservices'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'ourservices/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: 'joinarmat'
    label: 'Join Armat'
    folder: 'content/joinarmat'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'joinarmat/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Background Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
  - name: 'contactus'
    label: 'Contact Us'
    folder: 'content/contactus'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'contactus/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Location', name: 'location', widget: 'string', required: true }
      - { label: 'Address', name: 'address', widget: 'string', required: true }
      - { label: 'Email', name: 'email', widget: 'string', required: true, allow_multiple: false }
      - { label: 'Working Days', name: 'date', widget: 'string', required: true }
      - { label: 'Number', name: 'number', widget: 'string', required: true }
      - { label: 'LinkedIn', name: 'linkedin', widget: 'string', required: true }
  - name: 'therapeuticareas'
    label: 'Therapeutic Areas'
    folder: 'content/therapeuticareas'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'therapeuticareas/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: true }
      - { label: 'Background Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
  - name: 'keytosuccess'
    label: 'Key to Success'
    folder: 'content/keytosuccess'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'keytosuccess/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: true }
      - { label: 'Background Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
  - name: 'whyjoin'
    label: 'Why Join'
    folder: 'content/whyjoin'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'whyjoin/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description ', name: 'description', widget: 'string', required: true }
      - { label: 'Icon', name: 'icon', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Sort Key', name: 'sortkey', widget: 'number', required: false }
  - name: 'ourvacancies'
    label: 'Our Vacancies'
    folder: 'content/ourvacancies'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'ourvacancies/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'markdown', required: true }
  - name: 'therootprogram'
    label: 'The Root program'
    folder: 'content/therootprogram'
    create: false
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'therootprogram/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
  - name: 'therootsubjects'
    label: 'The Root Subjects'
    folder: 'content/therootsubjects'
    create: true
    editor:
      preview: false
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'therootsubjects/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - label: 'subjects'
        name: 'Subjects'
        widget: 'list'
        summary: '{{fields.title}}'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'markdown', required: true }
